orchestrator:
  build: .
  links:
    - keystone
    - keypass 
  ports:
    - "8084:8084"
  command: -keystonehost keypass \
           -keypasshost keypass

keypass:
  image: telefonicaiot/keypass

keystone:
  image: telefonicaiot/keystone
