orchestrator:
  image: telefonicaiot/orchestrator
  links:
    - keystone
    - keypass 
  ports:
    - "8084:8084"
  command: -keystonehost keypass \
           -keypasshost keypass

keypass:
  image: telefonicaiot/fiware-keypass

keystone:
  image: telefonicaiot/fiware-keystone-spassword
