mongo:
  image: mongo:3.2

orion:
  image: fiware/orion
  links:
    - mongo
    - perseo-fe
  ports:
    - "1026:1026"
  command: -dbhost mongo

mysql:
  image: mysql
  expose:
    - "3306"
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: iotonpremise
    MYSQL_DATABASE: keypass
    MYSQL_USER: keypass
    MYSQL_PASSWORD: keypass

keypass:
  image: telefonicaiot/fiware-keypass
  links:
    - mysql
  expose:
    - "7070"
    - "7071"
  ports:
    - "7070:7070"
    - "7071:7071"
  command: -dbhost mysql

keystone:
  image: telefonicaiot/fiware-keystone-spassword
  expose:
    - "5001"
  links:
    - mysql
  ports:
    - "5001:5001"
  command: -dbhost mysql

orchestrator:
  image: telefonicaiot/orchestrator
  expose:
    - "8084"
  links:
    - keystone
    - keypass
    - orion
  ports:
    - "8084:8084"
  command: -keystonehost keystone -keypasshost keypass -orionhost orion


portal:
  image: telefonicaiot/portal:develop
  links:
    - keystone
    - orion
    - orchestrator
  ports:
    - "80:80"
    - "8008:8008"
    - "443:443"
  environment:
    - portal_hostname=my_iot_portal
  command: -urlcep localhost:9090 -urlidm keystone:5001 -urlcb orion:1026 -urlorc orchestrator:8084 -urliot localhost:8081 -urlsth localhost:8666


perseo-core:
  image: telefonicaiot/perseo-core:develop
  ports:
    - "8080:8080"
  command: -perseo_fe_url 172.17.0.1:19090

perseo-fe:
  image: telefonicaiot/perseo-fe:develop
  links:
    - perseo-core
    - mongo
  ports:
    - "127.0.0.1:19090:9090"
  environment:
    - PERSEO_MONGO_HOST=mongo
    - PERSEO_CORE_URL=http://perseo-core:8080
    - PERSEO_NOTICES_PATH=/notices

pep-perseo-fe:
  image: telefonicaiot/fiware-pep-steelskin:develop
  links:
    - perseo-fe
    - keystone
    - keypass
  ports:
    - "9090:1026"
    - "11213:11211"
  environment:
    - COMPONENT_PLUGIN=perseo
    - TARGET_HOST=perseo-fe
    - TARGET_PORT=9090
    - PROXY_USERNAME=pep
    - PROXY_PASSWORD=4pass1w0rd
    - ACCESS_HOST=keypass
    - ACCESS_PORT=7070
    - AUTHENTICATION_HOST=keystone
    - AUTHENTICATION_PORT=5001
